# Generated by Django 3.2.11 on 2022-03-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.PositiveIntegerField(default=0)),
                ('reduction', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
                ('dernier_sold', models.DateTimeField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livres.auteur')),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livres.editeur')),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livres.object')),
            ],
        ),
    ]
