# Generated by Django 3.2.11 on 2022-03-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='livres.auteur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dernier_sold',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='editeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='livres.editeur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='livres.object'),
        ),
        migrations.AlterField(
            model_name='book',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
