# Generated by Django 3.2.11 on 2022-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_auto_20220301_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
