# Generated by Django 3.2.11 on 2022-03-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_alter_book_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='objet',
            new_name='categorie',
        ),
    ]
